[package]
name = "system"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
serde = { version = "1", features = ["derive"] }
sysinfo = { version = "0.30", default-features = false, features = ["multithread"] }
overflow-core = { path = "../core" }
overflow-utils = { path = "../utils" }
tracing = "0.1"
serde_json = "1"

[dev-dependencies]
serial_test = "2"
criterion = "0.5"

[features]
default = []
# When you later add AnyEvent::SystemStatSnapshot to overflow-core, we can enable this:
core-integration = []
